/* SEA-PIRATES sprite data — generated pixel maps. */
window.SP_PALETTE = {"K":"#160F08","L":"#7A4A26","D":"#4A2C18","d":"#2E1B0F","W":"#E8DCC0","S":"#C4B393","s":"#9C8B6E","R":"#C22B32","r":"#8A1C22","B":"#14100E","Y":"#F5B93C","y":"#8A6420","G":"#0A0705","C":"#3A3E4A","c":"#22252E","F":"#BFE9F5","g":"#7FE3C8","e":"#3E8C78","P":"#C79BF5","p":"#6A4A9E","E":"#FFE08A","N":"#2A3A6E","n":"#16224A","T":"#F2E3C0","t":"#C9A882","a":"#2FA07E","b":"#12604E","m":"#7A3A8E","X":"#C0392B","x":"#F5A030"};
window.SP_GHOST_OVERRIDE = {"K":"#0A1F1C","L":"#2E6E5E","D":"#1E5248","d":"#103028","W":"#9FE8D4","S":"#5FBBA0","s":"#3E8C78","R":"#2FA07E","r":"#17634C","B":"#06180F","Y":"#7FE3C8","y":"#2E7A64","G":"#04140F","F":"#BFF5E8","C":"#2E5A54","c":"#173830","N":"#1E5248","n":"#103028"};
window.SP_ROWS = {
  galleon: { w: 38, h: 26, rows: ["................BBWBBB................","................BBBB..................","................K.....................","................K.....................","................K.....................","...........K....K....K................","...........KKKKKKKKKKK.....K..........","............SSSSKSSSSS.....K..........","............WWWSKWWWWW.K...K...K......","...DDDDDDDDDWWWSKWWWWW.KKKKKKKKK..LLKK","....DDDDDDDDRRRRKRRRRR..SSSKSSSS......","....LYYLYYLLRRRRKRRRRR..WWSKWWWW......","....LYYLYYLLWWWWKWWWWW..RRSKRRRRLLL...","..LLLyyLyyLLWWWSKWWWWW..RRSKRRRRDDDD..","..LYDDDDDDDDsssSKsssss..WWSKWWWWDDDDD.","..DDDDDDLLLLLLLLKLLLLLLLssSKssssLLLLL.","..DDDDDDDDDDDDDDKDDDDDDDDDDKDDDDDDDDD.","...DDDDDGGDDGGDDGGDDGGDDGGDDGGDDDDDDD.","...DDDDDGGDDGGDDGGDDGGDDGGDDGGDDDDDD..","....DDDDDLLLLLLLLLLLLLDDDLLLLLLLDDDD..",".....dddddddddddddddddddddddddddddd...","........dddddddddddddddddddddddd......","FFFFF.............................FFFF",".FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF....","....FFFFFFFFFFFFFFFFFFFFFFFFFFF.......","......................................"] },
  skiff: { w: 16, h: 12, rows: [".........RRRR...",".........RR.....",".....ssssKss....",".....S.SSKSS....",".....SSSSK.S....","..LLLssssKss....","..DDDDDDDKDD....",".ddddddddKddd...",".KKKKKKKKKKKK...","................","FFFFFFFFFFFF....","................"] },
  frigate: { w: 44, h: 30, rows: ["....................NNYNYNYN................","....................NNNNNNNN................","....................K.......................","....................K.......................","........K...........K.......................","...KKKKKKKKKK.......K..........K............","....SSSSKSS...K.....K.....K....K............","....WWWWKWW...KKKKKKKKKKKKK....K............","....WWWWKWW....SSSSSKSSSSS.....K............","....ssssKss....WWWWWKWWWWWK....K.....K......","........K......WWWWWKWWWWWKKKKKKKKKKKK....LL","..WWWWWWKWWWW..WWWWWKWWWWW.SSSSKSSSSS...LLL.","...nnnnnKnnn...NNNNNKNNNNN.WWWWKWWWWW...LLL.","...NYYNYYNNN...NNNNNKNNNNN.NNNNKNNNNN.......","...NYYNYYNNN...WWWWWKWWWWW.NNNNKNNNNNNNN....",".nnNNNNNNNNN...WWWWWKWWWWW.WWWWKWWWWWNNNN...",".nnNYYNYYNNN...sssssKsssss.ssssKsssss.nnnn..",".nnnYYnYYnnn........K..........K......nnnn..","......nnnnnnnnnnnnnnKnnnnnnnnnnKnnnnnn......","....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.....","...NWWGGWWGGWWGGWWGGWWGGWWGGWWGGWWGGWWNN....","...NWWGGWWGGWWGGWWGGWWGGWWGGWWGGWWGGWWNN....","...NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN....","....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.....","......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.......","..........nnnnnnnnnnnnnnnnnnnnnnnn..........","FFFFFF..................................FFFF",".FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF....",".....FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF........","............................................"] },
  siren: { w: 12, h: 16, rows: ["............","...mmmmmm...","...mTTTTm...",".mmmKTTKmmm.",".mmmtTTtmmm.",".mmmTTTTmmm.",".mmmTrrTmmm.",".mmmTTTTmmm.",".mmmTTTTmmm.",".mmaaaaaamm.","...aaaaaa...","...aababa...","..aaaaaaaa..",".bbbbbbbbb..","...aaaaaaaa.",".....bbbbbb."] },
  tentacle: { w: 16, h: 44, rows: [".....pPEEp......",".....pEEEE......",".....pPPPp......",".....pPPPPp.....",".....pPPPPp.....",".....pPPPPp.....",".....pPPPPp.....",".....pPPPPp.....","....pPPEPPp.....","....pPEPPPp.....","....pPPPPPp.....","....pPPPPPp.....","....pPPPPPPp....","....pPPPEPPp....","....pPPEPPPp....","....pPPPPPPp....","....pPPPPPPp....","...pPPPPPPPp....","...pPPPEPPPp....","...pPPEPPPPp....","...pPPPPPPPp....","...pPPPPPPPp....","...pPPPPPPPPp...","...pPPPPEPPPp...","...pPPPEPPPPp...","...pPPPPPPPPp...","...pPPPPPPPPp...","..pPPPPPPPPPp...","..pPPPPEPPPPp...","..pPPPEPPPPPp...","..pPPPPPPPPPp...","..pPPPPPPPPPp...","..pPPPPPPPPPPp..","..pPPPPPEPPPPp..","..pPPPPEPPPPPp..","..pPPPPPPPPPPp..",".pPPPPPPPPPPPp..",".pPPPPPPPPPPPp..",".pPPPPPEPPPPPp..",".pPPPPEPPPPPPp..",".pPPPPPPPPPPPp..",".pPPPPPPPPPPPPp.",".pPPPPPPPPPPPPp.",".pPPPPPPEPPPPPp."] },
  kraken: { w: 56, h: 30, rows: ["........................................................","............................p...........................",".....................ppppppppppppppp....................","...................ppppppppppppppppppp..................",".................pppppppppppPppppppppppp................","...............pppppppPPPPPPPPPPPPPppppppp..............","..............ppppppppppppPPPPppppppppppppp.............",".............pppppPPPPPPPPPPPPPPPPPPPPPppppp............","............ppppPPPPEPPPPPPPPPPPPPPPEPPPPpppp...........","............ppppPEEEEKEEPPPPPPPPPEEKEEEEPpppp...........","...........ppppPEEEEKKKEEPPPPPPPEEKKKEEEEPpppp..........","...........pppPPEEEEKKKEEPPPPPPPEEKKKEEEEPPppp..........","...........pppPEEEEKKKKKEEPPPPPEEKKKKKEEEEPppp..........","..........ppppPPEEEEKKKEEPPPPPPPEEKKKEEEEPPpppp.........","...........ppPPPEEEEKKKEEPPPPPPPEEKKKEEEEPPPpp..........","...........pppPPPEEEEKEEPPPPPPPPPEEKEEEEPPPppp..........","...........pppPPPPPPEPPPPPPPPPPPPPPPEPPPPPPppp..........","............ppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpp...........","....Ppp....PpppPPPPPPPPPKKKKKKKKPPPPPPPPPPpppp....Ppp...","....Ppp....PppppPPPPPPPPKccccccKPPPPPPPPPppppp....Ppp...","....Pppp...PppppPPPPPPPPKcKKKKcKPPPPPPPPPppPppp...Pppp..","....Pppp...PppppppPPPPPPKccccccKPPPPPPPppp.Pppp...Pppp..","....Pppp...Pppp..ppPPPPPKKKKKKKKPPPPPPpp...Pppp...Pppp..","....Ppppp..Ppppp...pppPPPPPPPPPPPPPppp.....Ppppp..Ppppp.","....Ppppp..Ppppp.....pppppppPppppppp.......Ppppp..Ppppp.","....Pppppp.Pppppp...........p..............Pppppp.Pppppp","....Pppppp.Pppppp..........................Pppppp.Pppppp","....Pppppp.Pppppp..........................Pppppp.Pppppp","....PppppppPpppppp.........................PppppppPppppp","....PppppppPpppppp.........................PppppppPppppp"] },
  crate: { w: 12, h: 12, rows: ["KKKKKKKKKKKK","KLLLLKKLLLLK","KLYDDKKDDYDK","KLDDDKKDDDDK","KLDDDKKDDDDK","KKKKKKKKKKKK","KKKKKKKKKKKK","KLDDDKKDDDDK","KLDDDKKDDDDK","KLYDDKKDDYDK","KLDDDKKDDDDK","KKKKKKKKKKKK"] },
  coin: { w: 6, h: 6, rows: [".yyyy.","yYEYYy","yEYYYy","yYYYYy","yYYYyy",".yyyy."] },
  ball: { w: 4, h: 4, rows: [".cc.","CKCC","CCCC",".cc."] },
};
